/**
 * withModularHeaders.js
 *
 * Expo config plugin — injects `use_modular_headers!` into the iOS Podfile
 * generated by Expo prebuild.
 *
 * Required for @react-native-firebase: FirebaseAuth, FirebaseAuthInterop,
 * FirebaseAppCheckInterop, GoogleUtilities, and RecaptchaInterop are Swift pods
 * that must define modules. Adding `use_modular_headers!` globally tells
 * CocoaPods to generate module maps for ALL pods, satisfying that requirement.
 *
 * Uses split/findIndex instead of regex so it works regardless of whitespace,
 * quote style, or template variant in the generated Podfile.
 */

const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const withModularHeaders = (config) => {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const podfilePath = path.join(
        config.modRequest.platformProjectRoot,
        'Podfile'
      );

      if (!fs.existsSync(podfilePath)) {
        console.warn(
          '[withModularHeaders] Podfile not found at: ' + podfilePath
        );
        return config;
      }

      const contents = fs.readFileSync(podfilePath, 'utf-8');

      // Idempotent: skip if already patched
      if (contents.includes('use_modular_headers!')) {
        console.log('[withModularHeaders] Podfile already contains use_modular_headers!, skipping.');
        return config;
      }

      // Find the `platform :ios` line using line-by-line scan (no regex fragility)
      const lines = contents.split('\n');
      const platformLineIndex = lines.findIndex((line) =>
        line.trim().startsWith('platform :ios')
      );

      if (platformLineIndex === -1) {
        console.warn(
          '[withModularHeaders] Could not find `platform :ios` line in Podfile. Skipping.'
        );
        return config;
      }

      // Insert use_modular_headers! on the line immediately after platform :ios
      lines.splice(platformLineIndex + 1, 0, 'use_modular_headers!');
      fs.writeFileSync(podfilePath, lines.join('\n'), 'utf-8');

      console.log(
        '[withModularHeaders] Successfully inserted use_modular_headers! after line ' +
          (platformLineIndex + 1) +
          ' in Podfile.'
      );

      return config;
    },
  ]);
};

module.exports = withModularHeaders;
